// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xakmtinokszprjelultw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhha210aW5va3N6cHJqZWx1bHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTQ0MjMsImV4cCI6MjA2NjI5MDQyM30.nzVIlsERn7lJxDcu_X2_c6d5yhF5_G5_Zuy-pPC8WMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);